### PR TITLE
Merge automated and manual testcases

### PR DESCRIPTION
**Pull request by roshanths**
Changes to be merged:
1) requirement files (.md and .py)
2) Vagrant files for K8S distributions
3) adash_manual.py (Manual testcases)
4) adash_on_k8s.py (Automated testcases)
5) adash_regression.py
6) SRS status updated to `public`

### CODE REVIEW

**Comment by ghjm** [comment]
I was able to take a look at this today but did not get as deep into it as I would have liked.  Here are my comments so far:

* We should move the Vagrant directories out of the top level folder - perhaps put them under `tests/vagrant`
* Similarly, move `adash_regression.py` and `argparser.py` under `tests`
* Is it possible to have a Docker image to run the Selenium tests in?  If not, then the Ubuntu-specific webdriver default should be changed since many people on this project don't run Ubuntu
* Can we have a Makefile target, perhaps named `make test-suite`, that runs the full suite of tests (at least the automated ones)?

**Comment by ghjm** [comment]
One more comment: If we're adding Python code to this repo, we should add at least `__pycache__/` and `*.py[cod]` to our `.gitignore`.

**Comment by roshanths** [comment]
Noted on that @ghjm,  I will make the changes accordingly and update the PR.

**Comment by roshanths** [comment]
This PR is been replaced by the PR : https://github.com/Altinity/altinity-dashboard/pull/267

**Pull request closed without merging**
